development:
  adapter: postgresql
  encoding: unicode
  database: cf-auth_development
  pool: 5
  username: cf-auth
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: cf-auth_test
  pool: 5
  username: cf-auth
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: cf-auth_production
  pool: 5
  username: cf-auth
  password:
